version: "3.6"
services:
  unifi:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MEM_LIMIT=1024M #optional
    volumes:
      - ${HOME}/docker/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped

  ovpn:
    image: ghcr.io/wfg/openvpn-client
    container_name: ovpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /home/josh/docker/ovpn:/data/vpn
    restart: unless-stopped
    environment:
      - KILL_SWITCH=on
      - SUBNETS=192.168.1.0/24
      - FORWARDED_PORTS=2970
    ports:
      - 1198:1198
      - 1198:1198/udp
      - 8088:8088 # qBT webui
      - 8112:8112 # deluge webui
      - 22146:22146
      - 6080:6080

  # qbt:
  #   image: ghcr.io/linuxserver/qbittorrent
  #   container_name: qbt
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - UMASK_SET=022
  #     - WEBUI_PORT=8088
  #   volumes:
  #     - ${HOME}/docker/qbt:/config
  #     - nfs-media/qb:/media/qb
  #   restart: unless-stopped
  #   network_mode: service:ovpn

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/docker/sonarr:/config
      - nfs-media:/media
    ports:
      - 8989:8989
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/docker/nzbget:/config
      - nfs-media:/media
    ports:
      - 9876:6789
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002 #optional
    volumes:
      - ${HOME}/docker/radarr:/config
      - nfs-media:/media
    ports:
      - 7878:7878
    restart: unless-stopped

  radarr4k:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002 #optional
    volumes:
      - ${HOME}/docker/radarr4k:/config
      - nfs-media:/media
    ports:
      - 7880:7880
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - ${HOME}/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=65537
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${HOME}/docker/deluge/config:/config
      - nfs-media:/media
    # ports:
    #   - 8112:8112
    #   - 6881:6881
    #   - 6881:6881/udp
    network_mode: service:ovpn
    restart: unless-stopped

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/docker/tautulli:/config
      - ${HOME}/docker/plexmediaserver/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped

  teslamate:
    image: teslamate/teslamate:latest
    container_name: teslamate
    restart: always
    # user: '1000:65537'
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate_postgres
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=192.168.1.6
      - CHECK_ORIGIN=true
      - TZ=${TZ}
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  teslamate_postgres:
    container_name: teslamate_postgres
    image: postgres:13
    restart: always
    # user: '1000:65537'
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  teslamate_grafana:
    image: teslamate/grafana:latest
    container_name: teslamate_grafana
    restart: always
    # user: '1000:65537'
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=secret
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate_postgres
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-new:/var/lib/grafana

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/linuxserver/homeassistant
    volumes:
      - ${HOME}/docker/homeassistant:/config
    environment:
      - PUID=1000
      - PGID=65537
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host

  deconz:
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - ${HOME}/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    image: marthoc/deconz
    environment:
      - DECONZ_WEB_PORT=8454
      - DECONZ_WS_PORT=8545
      - DECONZ_DEVICE=/dev/ttyACM0

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=latest
      # - PLEX_CLAIM= #optional
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${HOME}/docker/plexmediaserver:/config
      - nfs-media:/media
    restart: unless-stopped

volumes:
  teslamate-db:
  teslamate-grafana-new:
  mosquitto-conf:
  mosquitto-data:
  nfs-media:
    driver_opts:
      type: nfs
      o: addr=192.168.1.5,rw,hard,intr
      device: :/volume1/media

  # npm:
  #   container_name: npm
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   ports:
  #     - '80:80'
  #     - '81:81'
  #     - '443:443'
  #   user: '1000:65537'
  #   environment:
  #     DB_MYSQL_HOST: "mariadb"
  #     DB_MYSQL_PORT: 3306
  #     DB_MYSQL_USER: "npm"
  #     DB_MYSQL_PASSWORD: "npm"
  #     DB_MYSQL_NAME: "npm"
  #   volumes:
  #     - ${HOME}/docker/npm:/data
  #     - ${HOME}/docker/npm/letsencrypt:/etc/letsencrypt
  # mariadb:
  #   container_name: mariadb
  #   image: 'jc21/mariadb-aria:latest'
  #   user: '1000:65537'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'npm'
  #     MYSQL_DATABASE: 'npm'
  #     MYSQL_USER: 'npm'
  #     MYSQL_PASSWORD: 'npm'
  #   volumes:
  #     - ${HOME}/docker/mariadb:/var/lib/mysql

  # bitwarden:
  #   image: vaultwarden/server:latest
  #   container_name: bitwarden
  #   restart: always
  #   user: '1000:65537'
  #   environment: 
  #     - WEBSOCKET_ENABLED=true
  #   volumes:
  #     - ${HOME}/docker/bitwarden:/data
  #   ports:
  #     - 7070:80

