---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: 'satrday.io'
subtitle: 'Homer'
logo: 'logo.png'
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
    light:
        highlight-primary: '#3367d6'
        highlight-secondary: '#4285f4'
        highlight-hover: '#5a95f5'
        background: '#f5f5f5'
        card-background: '#ffffff'
        text: '#363636'
        text-header: '#ffffff'
        text-title: '#303030'
        text-subtitle: '#424242'
        card-shadow: rgba(0, 0, 0, 0.1)
        link: '#3273dc'
        link-hover: '#363636'
    dark:
        highlight-primary: '#3367d6'
        highlight-secondary: '#4285f4'
        highlight-hover: '#5a95f5'
        background: '#131313'
        card-background: '#2b2b2b'
        text: '#eaeaea'
        text-header: '#ffffff'
        text-title: '#fafafa'
        text-subtitle: '#f5f5f5'
        card-shadow: rgba(0, 0, 0, 0.4)
        link: '#3273dc'
        link-hover: '#ffdd57'

# Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
    - name: 'Contribute'
      icon: 'fab fa-github'
      url: 'https://github.com/bastienwirtz/homer'
      target: '_blank' # optional html a tag target attribute
    - name: 'Wiki'
      icon: 'fas fa-book'
      url: 'https://www.wikipedia.org/'
    # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
    # see url field and assets/additional-page.yml.dist used in this example:
    #- name: "another page!"
    #  icon: "fas fa-file-alt"
    #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
    - name: 'Applications'
      icon: 'fas fa-cloud'
      items:
          - name: 'Healthchecks'
            url: 'https://healthchecks.io/projects/461e3564-28fe-4dc8-b592-81c54b4ab807/checks/'
            logo: 'https://healthchecks.io/static/img/logo-rounded-ua.svg'
            subtitle: 'Host uptime'
            tag: 'app'
        
          - name: 'Home Assistant'
            url: 'http://10.17.50.11:8123/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/home-assistant.svg'
            subtitle: ''
            tag: 'app'
            keywords: 'self hosted reddit'
            target: '_new' # optional html a tag target attribute

          - name: 'Nginx Proxy Manager'
            url: 'https://npm.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/png/nginxproxymanager.png'
            subtitle: 'proxy apps in LAN'
            tag: 'app'

          - name: 'Proxmox | rohan'
            url: 'https://rohan.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/proxmox.svg'
            subtitle: 'smart home containers'
            tag: 'app'

          - name: 'Proxmox | shire'
            url: 'https://shire.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/proxmox.svg'
            subtitle: 'media and game containers'
            tag: 'app'

          - name: 'PufferPanel'
            url: 'https://puff.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/pufferpanel/pufferpanel/7615ad6ab721fcd43a78a3a83445af68b3ac7607/client/frontend/public/img/appicons/144.png'
            subtitle: ''
            tag: 'app'

          - name: 'rey | DSM'
            url: 'http://rey.satrday.io:5000/'
            logo: 'assets/icons/dsm.png'
            subtitle: ''
            tag: 'app'

          - name: 'rey | files'
            url: 'http://rey.satrday.io/file/'
            logo: 'assets/icons/dsm.png'
            subtitle: ''
            tag: 'app'

          - name: 'Scrypted'
            url: 'https://10.17.50.8:10443/'
            logo: 'https://www.scrypted.app/images/web_hi_res_512.png'
            subtitle: 'camera integration'
            tag: 'app'

          - name: 'Teslamate'
            url: 'https://tesla.lan.satrday.io'
            logo: 'https://docs.teslamate.org/img/logo.svg'
            subtitle: ''
            tag: 'app'

          - name: 'Unifi'
            url: 'https://unifi.ui.com/'
            logo: 'assets/icons/unifi.png'
            subtitle: ''
            tag: 'app'

          - name: 'Unifi | local'
            url: 'https://10.17.10.1/'
            logo: 'assets/icons/unifi.png'
            subtitle: ''
            tag: 'app'

          - name: 'Uptime Kuma'
            url: 'https://status.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/uptimekuma.svg'
            subtitle: ''
            tag: 'app'

    - name: 'Media'
      icon: 'fas fa-film'
      items:
          - name: 'bazarr'
            url: 'http://10.17.50.6:6767/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/bazarr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'calibre-web'
            url: 'https://books.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/calibreweb.svg'
            subtitle: ''
            tag: 'app'

          - name: 'jackett'
            url: 'http://10.17.50.6:9117/'
            logo: 'https://avatars.githubusercontent.com/u/15383019?s=400&v=4'
            subtitle: ''
            tag: 'app'

          - name: 'Overseerr'
            url: 'https://tv.satrday.io/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/overseerr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'prowlarr'
            url: 'http://10.17.50.6:9696/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/prowlarr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'qBt'
            url: 'http://10.17.50.6:8202/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/qbittorrent.svg'
            subtitle: ''
            tag: 'app'

          - name: 'radarr'
            url: 'https://radarr.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/radarr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'radarr 4k'
            url: 'http://10.17.50.6:7880/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/radarr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'readarr'
            url: 'https://readarr.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/readarr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'SABnzbd'
            url: 'http://10.17.50.6:8080/'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/sabnzbd.svg'
            subtitle: ''
            tag: 'app'

          - name: 'Servarr'
            url: 'https://wiki.servarr.com/'
            logo: 'https://github.com/Servarr/Wiki/raw/master/assets/servarr/servarr_dark_1024.png'
            subtitle: 'arr wiki'
            tag: 'app'

          - name: 'sonarr'
            url: 'https://sonarr.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/sonarr.svg'
            subtitle: ''
            tag: 'app'

          - name: 'Tautulli'
            url: 'https://tau.lan.satrday.io'
            logo: 'https://raw.githubusercontent.com/NX211/homer-icons/master/svg/tautulli.svg'
            subtitle: ''
            tag: 'app'

